export interface Receptionist {
    Id?: number; // Optional because it's generated by backend
    firstName: string;
    middleName?: string;
    lastName: string;
    email: string;
    phone: string;
    password: string;
    gender?: 'MALE' | 'FEMALE' | 'OTHER'; // Based on your Gender Enum
    joiningDate: string; // Format: 'yyyy-MM-dd'
    photoURL?: string;
    role: 'STAFF'; // Since role is fixed for this entity
  }
  